SimpleSternia.Lines = {
    -- Generic
    -- Knighthood
    ["Knighthood"] = {
        {"Strike",
            [[^Focusing on \w+ (?<LIMB>.+), (?<ATTACKER>\w+) strike at (?<VICTIM>\w+) with .+\.$]],
            [[^With a focused look, (?<ATTACKER>\w+) strikes at (?<VICTIM>\w+) (?<LIMB>.+) with .+\.$]],
            nil,
        },
        {"Raze(Speed)",
            [[^(?<ATTACKER>\w+) raze (?<VICTIM>\w+)'s speed defence with .+\.$]],
            [[^(?<ATTACKER>\w+) razes (?<VICTIM>\w+) speed defence with .+\.$]],
            nil,
        },
        {"Raze(Shield)",
            [[^(?<ATTACKER>\w+) raze (?<VICTIM>\w+)'s magical shield with .+\.$]],
            [[^(?<ATTACKER>\w+) razes (?<VICTIM>\w+) magical shield with .+\.]],
            nil,
        },
        {"Raze",
            [[^(?<ATTACKER>\w+) whip .+ through the air in front of (?<VICTIM>\w+), to no effect\.$]],
            [[]],
            [[]],
        },
    },
    ["Axelord"] = {
        {"Swing",
            [[^(?<ATTACKER>\w+) hack into (?<VICTIM>\w+) with your axe, spraying blood as you shear \w+ (?<LIMB>.+)\.$]],
            [[^(?<ATTACKER>\w+) hacks into (?<VICTIM>\w+) with \w+ axe, spraying blood as \w+ shears your (?<LIMB>.+), leaving it (?<WOUNDS>.+)\.$]],
            nil,
        },
        {"Sliceforehead",
            [[^(?<ATTACKER>\w+) slash across (?<VICTIM>\w+)'s forehead leaving a long furrow that weeps blood onto \w+ face.$]],
            [[^A slash across (?<VICTIM>\w+) forehead leaves a long furrow that weeps blood onto your face\.$]],
            nil,
        },
        {"Severphrenic",
            [[^(?<ATTACKER>\w+) hack through (?<VICTIM>\w+)'s midriff, drawing your blade out in a spray of crimson blood as \w+ wheezes to breathe\.$]],
            [[^(?<ATTACKER>\w+) hacks through (?<VICTIM>\w+) midriff, drawing \w+ blade out in a spray of crimson blood as your lungs wheeze to breathe\.$]],
            nil,
        },
        {"Upsetstomach",
            [[^(?<ATTACKER>\w+) heave your axe into (?<VICTIM>\w+)'s gut which causes \w+ to spit up bloody bile\.$]],
            [[^(?<ATTACKER>\w+) heaves \w+ axe into your gut, causing (?<VICTIM>\w+) to spit up bloody bile\.$]],
            nil,
        },
        {"Breakarm",
            [[^(?<ATTACKER>\w+) strike into (?<VICTIM>\w+)'s (?<LIMB>left arm|right arm), which breaks with a loud crack\.$]],
            [[^(?<ATTACKER>\w+) strikes into (?<VICTIM>\w+) (?<LIMB>left arm|right arm), breaking it with a loud crack\.$]],
            nil,
        },
        {"Knockdown",
            [[^With an elegant stroke, (?<ATTACKER>\w+) sweep (?<VICTIM>\w+)'s leg out from under \w+, knocking \w+ to the ground\.$]],
            [[^With an elegant stroke,  (?<ATTACKER>\w+) sweeps your legs out from under (?<VICTIM>\w+), knocking you to the ground\.$]],
            nil,
        },
        {"Sweep",
            [[^Sweeping your axe through the air, (?<ATTACKER>\w+) send it whooshing straight into (?<VICTIM>\w+)'s (?<LIMB>.+)\.$]],
            [[^Sweeping \w+ axe through the air, (?<ATTACKER>\w+) sends it whooshing straight into (?<VICTIM>\w+) (?<LIMB>.+), leaving it (?<WOUNDS>.+)\.$]],
            nil,
        },
        {"Slitthroat",
            [[^(?<VICTIM>\w+) hack into (?<ATTACKER>\w+)'s neck and blood fountains out in a thick spray\.$]],
            [[^(?<VICTIM>\w+) hacks into (?<ATTACKER>\w+) neck and blood fountains out in a thick spray\.$]],
            nil,
        },
        {"Gashchest",
            [[^(?<ATTACKER>\w+) slash through (?<VICTIM>\w+)'s chest, gashing apart layers of skin to reveal \w+ bloody ribcage\.$]],
            [[^(?<VICTIM>\w+) slashes through (?<ATTACKER>\w+) chest, gashing apart layers of skin to reveal your bloody ribcage\.$]],
            nil,
        },
        {"Disembowel",
            [[^(?<ATTACKER>\w+) blade burrows into (?<VICTIM>\w+)'s gut and coils of bloody intestines spill out in a grotesque mass\.$]],
            [[^(?<ATTACKER>\w+)'s blade burrows into (?<VICTIM>\w+) gut and coils of bloody intestines spill out in a grotesque mass.$]],
            nil,
        },
        {"Whack",
            [[^(?<ATTACKER>\w+) turn .+ to the side and slam it into (?<VICTIM>\w+)'s head, leaving \w+ stunned and confused\.$]],
            [[^(?<ATTACKER>\w+) turns .+ to the side and slams it into your head, leaving (?<VICTIM>\w+) stunned and confused\.$]],
            nil,
        },
        {"Legtendon",
            [[^(?<ATTACKER>\w+) hack the tendon above (?<VICTIM>\w+)'s (?<LIMB>left|right) heel, making \w+ scream as it is completely severed\.$]],
            [[^(?<ATTACKER>\w+) hacks the tendon above (?<VICTIM>\w+) (?<LIMB>left|right) heel and you scream in agony as it is completely severed\.$]],
            nil,
        },
        {"Amputatearm",
            [[^(?<VICTIM>\w+)'s (?<LIMB>left arm|right arm) is completely cut through, flying through the air as blood splurts out in a fountain at the severed shoulder joint\.$]],
            [[^(?<ATTACKER>\w+) cuts completely through (?<VICTIM>\w+) (?<LIMB>left arm|right arm), which flies through the air as blood splurts out in a fountain at the severed shoulder joint\.$]],
            nil,
        },

    },
    -- Mage
        --Aquamancy
        --Geomancy
        --Pyromancy
        --Aeromancy
    -- Druidry
        -- BlackTalon
        -- Hartstone
    -- Wicca
        -- Night
        -- Moon
    -- Cosmic
    ["Cosmic"] = {
        {"Cosmicfire", 
            [[^(?<ATTACKER>\w+) allow an infinitesimally small mote of cosmic fire to manifest and direct it at (?<VICTIM>\w+). Cosmic fire blasts forth, dissolving \w+ flesh in a sparkling current of energy\.$]],
            [[^(?<ATTACKER>\w+) raises a palm which glows with a tiny pinpoint of light. The light turns into a sparkling current of energy that slams into (?<VICTIM>\w+), dissolving your flesh\.$]],
            [[^(?<ATTACKER>\w+) raises a palm which glows with a tiny pinpoint of light. The light turns into a sparkling current of energy that slams into (?<VICTIM>\w+), dissolving (his|her|their) flesh\.$]],
        },
        {"Sleep",
            [[^(?<ATTACKER>\w+) tug at the cosmic fabric that binds (?<VICTIM>\w+), in an effort to send \w+ to sleep\.$]],
            [[^(?<ATTACKER>\w+) reaches over and gently squeezes your shoulder. (?<VICTIM>\w+) find yourself rapidly becoming sleepier and sleepier.$]],
            nil,
        },
        {"Fear",
            [[^Becoming one with the cosmos, (?<ATTACKER>\w+) allow the awesome power of the cosmos to be reflected through your eyes\.$]],
            nil,
            [[^(?<ATTACKER>\w+) shuts \w+ eyes for several moments, then opens them and reveals glowing orbs of static energy rolling in \w+ eyesockets\.$]],
        },
        {"Web",
            [[^(?<ATTACKER>\w+) grasp a handful of cosmic threads and will them into existence, then release them onto (?<VICTIM>\w+) as a mass of sticky webs\.$]],
            [[^Sticky strands of webbing spray out from (?<ATTACKER>\w+) to cover (?<VICTIM>\w+)\.$]],
            nil,
        },
    },
        --Harmonics
    ["Harmonics"] = {
        {"Malefactgem",
            [[^(?<ATTACKER>\w+) fold the charged crystals together, forming a malefactgem. You smash it at your feet and red and black smoke roils about you\.$]],
            [[^Tendrils of red and black smoke wrap around (?<VICTIM>\w+), covering your skin in a sticky film\.$]],
            [[^(?<ATTACKER>\w+) smashes a chunk of dark rock at his feet and red and black smoke roils about \w+\.$]],
        },
        {"Shockstone",
            [[^(?<ATTACKER>\w+) fold the charged crystals together, forming a shockstone. You throw it at (?<VICTIM>\w+), and it shatters, releasing a flurry of brilliant sapphire rays.$]],
            [[^(?<ATTACKER>\w+) tosses a delicate blue sphere into the air at (?<VICTIM>\w+), which shatters in a flurry of brilliant sapphire rays.$]],
            nil,
        },
    },

    -- Rituals
        --Aeonics
    ["Aeonics"] = {
        {"Aeon",
            [[^Locking your eyes with (?<VICTIM>\w+), (?<ATTACKER>\w+) click your tongue against the roof of your mouth, synchronising the rhythm with \w+'s inner clock. You throw the rhythm off-beat and watch as \w+ becomes lost in an aeonic field\.$]],
            [[^Locking \w+ eyes with (?<VICTIM>\w+), (?<ATTACKER>\w+) clicks his tongue against the roof of \w+ mouth. As the rhythm of the clicks slows down, reality seems to stop and start in sudden jerks\.$]],
            nil,
        },
        {"Inisght",
            [[(?<ATTACKER>\w+) close your eyes and focus on the inner turmoil of your own mind, forcing your disordered thoughts into cohesion. Basking in the symmetry of that formation, you find you have far greater insight into your own being than before\.$]],
            nil,
            [[^(?<ATTACKER>\w+) closes \w+ eyes and frowns briefly at some secret thought, before \w+ brow smooths out and \w+ appears at peace\.$]],
        },
        {"Timewarp",
            [[^With several languid gestures, (?<ATTACKER>\w+) twist the temporal field that surrounds (?<VICTIM>\w+), causing time itself to warp around \w+\.$]],
            [[^(?<ATTACKER>\w+) languidly gestures at (?<VICTIM>\w+) and the world tilts as time itself warps\.$]],
            nil,
        },
        {"Singularity",
            [[^(?<ATTACKER>\w+) focus inward, compressing time connecting to (?<VICTIM>\w+) into a single point, and let it float out in front of you\.$]],
            [[^(?<VICTIM>\w+) feel something tugging on you as (?<ATTACKER>\w+) releases something floating in front of \w+\.$]],
            nil,
        },
        {"Oracle",
            [[^(?<ATTACKER>\w+) gaze deep into the eyes of (?<VICTIM>\w+), revealing the darkest possible timelines open to \w+\.$]],
            [[^(?<ATTACKER>\w+) gazes deep into (?<VICTIM>\w+) eyes, revealing oracular visions of the darkest possible of futures\.$]],
            nil,
        },
        {"Chronicloop",
            [[^(?<ATTACKER>\w+) look straight at (?<VICTIM>\w+) and wave your arms in a circular motion, willing the time surrounding \w+ to loop and spin unto itself\.$]],
            [[^(?<ATTACKER>\w+) looks straight at (?<VICTIM>\w+) and waves his arms in a circular motion, and you notice time begin to spin around you\.$]],
            nil
        },
        {"PopChronicloop",
            nil,
            [[^The time looping around (?<VICTIM>\w+) spins faster and faster before imploding in on you. You find yourself reliving moments that just passed again\.$]],
            [[^The time looping around (?<VICTIM>\w+) spins faster and faster before imploding in on \w+\.$]],
        },
        {"Blink",
            [[^(?<ATTACKER>\w+) close your eyes in concentration and reach in front of you, trying to find the strand of time that will let you intercept your quarry\.$]],
            nil,
            [[^(?<ATTACKER>\w+) closes \w+ eyes in concentration, reaching \w+ hands out and grabbing onto something you cannot see.$]],
        },
    },
        -- Sacraments
    ["Sacraments"] = {
        {"Holybeing",
            [[^You bow your head and begin to chant a prayer to the Holy Supernals, beseeching them to imbue your mortal soul with the radiance of the Light. An indescribable warmth and comfort envelops you as your senses suddenly expand, golden motes of light racing down your skin as you open your eyes, gazing out upon the world with a renewed and sacrosanct presence\.$]],
            nil,
            [[^(?<ATTACKER>\w+) chants a vibrant prayer to the Holy Supernals, beseeching them to heal you of your wounds. Suddenly \w+ eyes go completely white as \w+ is limned in a Holy Light which soon dissipates into a fine mist that rolls down \w+ arms to cover you, bathing you in its curative powers\.$]],
        },
        {"Righteousblade",
            [[^(?<ATTACKER>\w+) hold your weapon up in the air, calling forth power. A moment later, holy energy shines from within the weapon, piercing the shadows with effulgent light\.$]],
            nil,
            [[^(?<ATTACKER>\w+) holds \w+ weapon up in the air. A moment later, holy energy shines from within the weapon, piercing the shadows with effulgent light.$]],
        },
        {"ProcRighteousblade",
            [[^As (?<ATTACKER>\w+) strike (?<VICTIM>\w+), \w+ \w+ briefly illuminated and struck by a bolt of blue lightning\.$]],
            [[^As (?<VICTIM>\w+) are struck, you see the vision of an angel who quickly strikes you with a bolt of blue lightning\.$]],
            nil,
        },
        {"Hallowedground",
            [[^With a whispered prayer and a delicate twist of your outstretched hand, (?<ATTACKER>\w+) send globes of light flying in each direction\.$]],
            nil,
            [[^Muttering prayers to \w+, (?<ATTACKER>\w+) slowly raises \w+ arms up from \w+ sides towards the heavens, and, as \w+ \w+ so, bright rays of holy light rise up from the ground\.$]],
        },
        {"Heretic",
            [[^(?<ATTACKER>\w+) brand (?<VICTIM>\w+) a heretic for \w+ crimes against the Light\.$]],
            [[^(?<ATTACKER>\w+) brands (?<VICTIM>\w+) a heretic for your crimes against the Light\.$]],
            [[^(?<ATTACKER>\w+) brands (?<VICTIM>\w+) a heretic for (his|her|their) crimes against the Light\.$]],
        },
        {"Infidel",
            [[^Having not learned the lessons of \w+ sins, (?<ATTACKER>\w+) mark the heretic (?<VICTIM>\w+) as an infidel for \w+ utter contempt for the Light\.$]],
            [[^(?<ATTACKER>\w+) marks (?<VICTIM>\w+) as an infidel for your utter contempt for the Light\.]],
            [[^(?<ATTACKER>\w+) marks (?<VICTIM>\w+) as an infidel for (his|her|their) utter contempt for the Light\.]],
        },
        {"Inquisition",
            [[^Having no other option, (?<ATTACKER>\w+) call down an inquisition upon (?<VICTIM>\w+). A pillar of holy fire strikes \w+ from the heavens, leaving \w+ standing there frozen with an expression of terror on \w+ face\.$]],
            [[^(?<ATTACKER>\w+) calls down an inquisition upon (?<VICTIM>\w+), and a pillar of holy fire strikes you from the heavens. A bright pain streaks through your body but you cannot move or even cry out in agony\.$]],
            [[^(?<ATTACKER>\w+) calls down an inquisition upon (?<VICTIM>\w+), and a pillar of holy fire strikes (him|her|them) from the heavens.\.$]], --unsure
        },
        {"Trueheal",
            [[^(?<ATTACKER>\w+) give yourself wholly unto the Light, and feel a divine presence fill you from brow to feet. As you are lifted off the ground, you turn slowly in utter ecstasy as the presence of the Supernals fill you with power and joy\.$]],
            nil,
            [[^(?<ATTACKER>\w+) stretches \w+ arms out to either side and drops \w+ head back with \w+ eyes closed. A blinding white light strikes \w+ on the forehead and travels to \w+ feet, lifting \w+ off the ground. As \w+ slowly turns, all \w+ wounds heal and a blazing aura pulsates around \w+\.$]],
        },

    },
        -- Aeonics

    --Org
    ["Hallifax"] = {
        {"Cloudberrytea",
            [[^A rush of icy air leaves (?<ATTACKER>\w+) pores and surrounds (?<VICTIM>\w+) in a frigid cloud, warping time around \w+\w.$]],
            [[^A rush of icy air leaves (?<ATTACKER>\w+)'s pores and surrounds (?<VICTIM>\w+) in a frigid cloud, warping time around you\.$]],
            nil,
        },
    },
}